# Generated by Django 6.0.2 on 2026-02-23 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_tagline', models.CharField(default='Web Design & Development', max_length=120)),
                ('hero_title', models.CharField(default='Launch Your Website in Days', max_length=160)),
                ('hero_paragraph', models.TextField(default='I provide professionally designed pre-built websites that help businesses go online quickly. No long development time. No high cost. Just ready-to-use solutions.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home content',
                'verbose_name_plural': 'Home content',
            },
        ),
        migrations.CreateModel(
            name='WebsiteTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Optional emoji or short label shown in the thumbnail.', max_length=4)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=160)),
                ('message', models.TextField()),
                ('plan', models.CharField(blank=True, help_text='Optional plan / offer code (from URL query).', max_length=80)),
                ('page', models.CharField(blank=True, help_text='Page where the inquiry was submitted.', max_length=120)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(blank=True, help_text='Template the customer is interested in (if any).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.websitetemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
